[Allagamento] [1] Pompieri:1,5;Ambulanza:1,2;
[Incendio] [2] Pompieri:5,1;Ambulanza:3,1;
[Sommossa] [2] Polizia:3,8;Ambulanza:2,4;
crozzi
[Incidente_Stradale] [0] Pompieri:2,6,7;Ambulanza:2,3sss;Polizia:1,4 pizza; Medico:1
[Tsunami] [2] Pompieri:3,10;Ambulanza:2,5;Medico:2,6;
[Ufo] [0] Pompieri:4,12;Ambulanza:3,7;Polizia:2,9;
[Tapiro] [2] Pompieri:6,15;Ambulanza:4,10;Polizia:3,8;Medico:2,5;
[Terremoto] [1] Pompieri:10,20;Ambulanza :8,15;Polizia:5,12;Medico:4,10;